language: c

compiler:
  - clang

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/

build:
  pre_ci_boot:
    image_name: drydock/u14cppall
    image_tag: tip
  ci:
    - shippable_retry sudo add-apt-repository ppa:beineri/opt-qt596-trusty -y
    - shippable_retry sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
    - shippable_retry sudo apt-get -y -qq update
    - shippable_retry sudo apt-get -y install build-essential software-properties-common cmake libgl1-mesa-dev libxss-dev qt59base qt59webengine qt59x11extras
    - source /opt/qt*/bin/qt*-env.sh
    - export PATH=/opt/qt59/bin:$PATH
    - SRC="cmake-build-relwithdebinfo"
    - CMAKE_NAME="TimeCampDesktop"
    - cp CMakeProjectConfig.cmake.example CMakeProjectConfig.cmake
    - mkdir -p $SRC
    - cd $SRC
    - cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Unix Makefiles" "../"
    - cd ../
    - cmake --build $SRC --target "${CMAKE_NAME}" --
